---
- name: Check/Repair Disk
  ansible.builtin.shell: yes | diskutil repairDisk "{{ physical_disk_id }}"

- name: Expand disk
  ansible.builtin.command: diskutil apfs resizeContainer "{{ disk_container }}" "{{ disk_size }}"
