- name: Install required packages
  ansible.builtin.package:
    name: cloud-utils-growpart
    state: present
  become: true

- name: Expand Linux Disk
  ansible.builtin.include_tasks:
    file: Linux.yml
